# Opérations sur les matrices avec numpy

In [2]:
# importation de la librairie 
import numpy as np

In [3]:
# Création d'un nobre (ou tableau de dimension 0)
arr=np.array(42)
print(arr)

42


In [4]:
# Création de tableau de dimension1 suivant(il
#contient des tableaux de dimension 0)

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
# Créer le tableau de dimension 2 suiavant(il
# contient des tableaux de dimension 1)

arr=np.array([
    [1,8,5],
    [4,6,4],
    [5,7,2]
])
print(arr)

[[1 8 5]
 [4 6 4]
 [5 7 2]]


In [9]:
# Créer le tableau de dimension 3 suiavant(il
# contient des tableaux de dimension 2)

arr=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
# Identifier la diension d'un tableau

a=np.array(52)
print('La dimension arr est:',a.ndim)

La dimension arr est: 0


In [11]:
b=np.array([1,2,3,4,5])
print('La dimension arr est:',b.ndim)

La dimension arr est: 1


In [12]:
c=np.array([
    [1,8,5],
    [4,6,4],
    [5,7,2]
])
print('La dimension arr est:',c.ndim)

La dimension arr est: 2


In [13]:
d=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print('La dimension arr est:',d.ndim)

La dimension arr est: 3


In [15]:
# Indexation
# Accéder aux éléments d'un tableau de dimension1
#Créer le tableau suivant et afficher les éléments pointés

arr=np.array([43,22,1,10,])

# Afficher 43
print(arr[0])

43


In [16]:
# Afficher 10
print(arr[3])

10


In [18]:
# Afficher 22
print(arr[1])

22


In [19]:
# Accès aux éléments d'un tableau de dimension2
# Créer le tableau suivant et afficher les éléments pointés

arr=np.array([
    [19,54,51],
    [45,15,21],
    [8,32,31]
])

# Afficher 19
print(arr[0,0])

19


In [20]:
# Afficher 51
print(arr[0,2])

51


In [22]:
# Accès aux éléments d'un tableau de dimension 3
# Créer le tableau suivant et afficher les éléments pointés


arr=np.array([
    [
        [20,23],
        [51,62]
    ],
    [
        [0,1],
        [0,1]
    ],
     [
        [3,8],
        [9,4]
    ]
])
# Afficher 23
print(arr[0,0,1])

23


In [23]:
# Afficher 51
print(arr[0,1,0])

51


In [24]:
# Afficher 0
print(arr[1,1,0])

0


In [25]:
# Afficher 1
print(arr[1,0,1])

1


In [26]:
# Afficher 8
print(arr[2,0,1])

8


In [28]:
# Afficher 9
print(arr[2,1,0])

9


In [3]:
# Utilistion des indices négatifs
tab=np.array([
    [
        [6,0,1],
        [0,-1,1],
        [1,1,3],
        [0,1,2],
        [1,0,1]
    ],
    [
        [1,0,1],
        [3,4,2],
        [2,1,0],
        [8,6,0],
        [9,5,4]
    ],
    
])
print(tab)

[[[ 6  0  1]
  [ 0 -1  1]
  [ 1  1  3]
  [ 0  1  2]
  [ 1  0  1]]

 [[ 1  0  1]
  [ 3  4  2]
  [ 2  1  0]
  [ 8  6  0]
  [ 9  5  4]]]


In [4]:
#Affichage de 2
# méthode1: utilisation d'indice positifs

print(tab[1,1,2])

2


In [5]:
# méthode2: utilisation d'indices négatifs

print(tab[-1,-4,-1])

2


In [7]:
## méthode3: utilisation simultanées d'indices négatifs et positifs

print(tab[1,1,-1])

2


# Extraction d'une tranche d'un tableau
 # Règle : syntaxe utilisé : [début : fin : pas]
  # - si le pas n'est pas précisé, il vaut 1 par défaut
  # - si la fin n'est pas précisé, tout le reste du tableau est considéré
  # - si le début n'est pas précisé, il vaut 0 par défaut c'est à dire le premier indice de position

# Extraction dans un tableau de dimension 1

In [8]:
#Exemple 
tab = np.array([6,43,51,22,3,12])
print(tab)

[ 6 43 51 22  3 12]


In [9]:
# extraction des 3 premier élément
# première méthode
print(tab[0:3])

[ 6 43 51]


In [10]:
# deuxième méthode
print(tab[:3])

[ 6 43 51]


In [12]:
print(tab[3:])

[22  3 12]


In [14]:
# extraction de tout les éléments avec un pas de 2
# première méthode
tab = np.array([8,10,14,21,30,40,55,33,11])
print(tab[0::2])

[ 8 14 30 55 11]


In [15]:
#deuxième méthode
print(tab[0:9:2])


[ 8 14 30 55 11]


In [16]:
#troisième méthode
print(tab[::2])

[ 8 14 30 55 11]


# Extraction dans un tableau de dimension 2

In [18]:
# soit le tableau de dimension 2 suivant 
tab = np.array([
    [3,7,1,5,9],
    [8,2,6,0,4]
])
print(tab)

[[3 7 1 5 9]
 [8 2 6 0 4]]


In [21]:
# extraire et afficher la trance [7,1,5]
print(tab[0,1:4])

[7 1 5]


In [22]:
# pour chaque sous tableau du tableau précedent, extraire l'élément se trouvant à la position 3
print(tab[0:2,3])

[5 0]


In [24]:
print(tab[:,3])

[5 0]


# Extraction dans un tableau de dimension 3

In [27]:
# soit le tableau
tab=np.array([
    [
        [6,0,1],
        [0,-1,1],
        [1,1,3],
        [0,1,2],
        [1,0,1]
    ],
    [
        [1,0,1],
        [3,4,2],
        [2,1,0],
        [8,6,0],
        [9,5,4]
    ],])

print(tab[1, 2 , :])

[2 1 0]


In [28]:
print(tab[1, 2 ])

[2 1 0]


In [29]:
print(tab[-1, 2 , : 3])

[2 1 0]


In [30]:
print(tab[1, 2 , 0 : 3])

[2 1 0]
